/home/yl254115/miniconda3/lib/python3.7/site-packages/mne/viz/evoked.py:2075: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=0, top=0
  orig_ymax if ymax is None else ymax)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
plot_rasters.py:139: RuntimeWarning: Cannot find channel coordinates in the supplied Evokeds. Not showing channel locations.
  fig = epochs_spikes.plot_image(cluster, order=IX, vmin=0, vmax=1, colorbar=False, show=False)
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
Traceback (most recent call last):
  File "plot_rasters.py", line 77, in <module>
    assert len(filename) == 1
AssertionError
